# Generated by Django 4.2.1 on 2023-06-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_product_productprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productprice',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='actual_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
