# Generated by Django 4.2.1 on 2023-06-14 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_delete_user_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.productprice')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('user_id', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=10)),
                ('seating_capacity', models.PositiveIntegerField()),
                ('is_occupied', models.BooleanField(default=False)),
                ('order_items', models.ManyToManyField(to='adminapp.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('order_type', models.CharField(choices=[('Home Delivery', 'Home Delivery'), ('Take Away', 'Take Away')], max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=20)),
                ('address_one', models.CharField(max_length=500)),
                ('address_two', models.CharField(max_length=500)),
                ('address_three', models.CharField(max_length=500)),
                ('order_note', models.CharField(max_length=500)),
                ('payment_mode', models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Card on Delivery', 'Card on Delivery')], max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('canceled', models.BooleanField(default=False)),
                ('order_items', models.ManyToManyField(to='adminapp.cart')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.user'),
        ),
    ]
