# Generated by Django 4.2.1 on 2023-06-14 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_cart_user_table_order_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_items',
            new_name='cart',
        ),
    ]
