# Generated by Django 4.2.1 on 2023-06-14 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_rename_order_items_order_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='order_items',
            new_name='cart',
        ),
    ]
