# Generated by Django 4.2.1 on 2023-06-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_order_total_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_cart',
        ),
    ]
