# Generated by Django 4.2.1 on 2023-06-14 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_order_total_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
