# Generated by Django 4.2.1 on 2023-06-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('order_type', models.CharField(choices=[('Home Delivery', 'Home Delivery'), ('Take Away', 'Take Away')], max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=20)),
                ('address_one', models.CharField(max_length=500)),
                ('address_two', models.CharField(max_length=500)),
                ('address_three', models.CharField(max_length=500)),
                ('order_note', models.CharField(max_length=500)),
                ('payment_mode', models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Card on Delivery', 'Card on Delivery')], max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('canceled', models.BooleanField(default=False)),
                ('total_cart', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cart', models.ManyToManyField(to='adminapp.cart')),
            ],
        ),
    ]
