# Generated by Django 4.2.1 on 2023-06-14 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0019_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_cart',
        ),
    ]
