# Generated by Django 4.2.1 on 2023-06-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_cart_product_price_dummy_cart_quantity_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity_dummy',
        ),
    ]
