# Generated by Django 4.2.1 on 2023-06-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0023_remove_cart_quantity_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='tax_dummy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
