# Generated by Django 4.2.1 on 2023-06-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0026_order_status_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('Order Don', 'Order Don'), ('Cancel', 'Cancel')], default='Pending', max_length=100, null=True),
        ),
    ]
