# Generated by Django 4.2.1 on 2023-07-04 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0031_alter_table_table_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='cart',
        ),
    ]
