# Generated by Django 4.2.1 on 2023-07-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0036_remove_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
