# Generated by Django 4.2.1 on 2023-07-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0038_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.CharField(max_length=5000, unique=True),
        ),
    ]
