# Generated by Django 4.2.1 on 2023-07-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0039_alter_table_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
