# Generated by Django 4.2.1 on 2023-07-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0041_alter_order_date_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference_number',
            field=models.CharField(max_length=100),
        ),
    ]
