# Generated by Django 4.2.1 on 2023-07-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0042_alter_order_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
