# Generated by Django 4.2.1 on 2023-07-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0043_order_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_three',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
