# Generated by Django 4.2.1 on 2023-07-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0044_alter_order_address_three_alter_order_order_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
